### ISSUE TITLE
-filter_complex missing end quotes

### ISSUE THREAD

**Issue by alanbqs** [Romander/ffmpeg-script-generator#1]
I have generated a test script using F1.AVI, F2.AVI and F3.AVI, but I notice that the last filter-complex shows ;\ instead of "

i.e.
`ffmpeg \
-vsync 0 \
-i "F2.AVI" \
-i "F3.AVI" \
-filter_complex \
"[0]settb=AVTB[0:v]; \
[1]settb=AVTB[1:v]; \
[0:v][1:v]xfade=transition=fade:duration=1:offset=9,format=yuv420p[video];\
-b:v 10M \
-map "[video]" "out.mp4" \`

instead of 

`ffmpeg \
-vsync 0 \
-i "F2.AVI" \
-i "F3.AVI" \
-filter_complex \
"[0]settb=AVTB[0:v]; \
[1]settb=AVTB[1:v]; \
[0:v][1:v]xfade=transition=fade:duration=1:offset=9,format=yuv420p[video]"
-b:v 10M \
-map "[video]" "out.mp4" \`
![image](https://user-images.githubusercontent.com/95624155/150806909-b030825e-fb22-4fe6-bb49-bff90cb54761.png)

++ ALSO : .... Why are there only 2 inputs to the video and audio commands - this does not seem right to me (it is missing F1.AVI)

**Comment by Romander** [comment]
> I have generated a test script using F1.AVI, F2.AVI and F3.AVI, but I notice that the last filter-complex shows ;\ instead of "
> 
> i.e. `ffmpeg \ -vsync 0 \ -i "F2.AVI" \ -i "F3.AVI" \ -filter_complex \ "[0]settb=AVTB[0:v]; \ [1]settb=AVTB[1:v]; \ [0:v][1:v]xfade=transition=fade:duration=1:offset=9,format=yuv420p[video];\ -b:v 10M \ -map "[video]" "out.mp4" \`
> 
> instead of
> 
> `ffmpeg \ -vsync 0 \ -i "F2.AVI" \ -i "F3.AVI" \ -filter_complex \ "[0]settb=AVTB[0:v]; \ [1]settb=AVTB[1:v]; \ [0:v][1:v]xfade=transition=fade:duration=1:offset=9,format=yuv420p[video]" -b:v 10M \ -map "[video]" "out.mp4" \` ![image](https://user-images.githubusercontent.com/95624155/150806909-b030825e-fb22-4fe6-bb49-bff90cb54761.png)
> 
> ++ ALSO : .... Why are there only 2 inputs to the video and audio commands - this does not seem right to me (it is missing F1.AVI)

Thanks! I will look into it

**Comment by alanbqs** [comment]
still seeing both the problems....

![image](https://user-images.githubusercontent.com/95624155/150842569-7792ed40-915b-4e2d-94d3-f253df54c132.png)

**Comment by Romander** [comment]
@alanbqs I've changed adding inputs logic for clearness and the closing quote should be there, try hard refresh, clear browser cache.

**Comment by alanbqs** [comment]
I'm just trying the new changes - and the video part runs with no errors (although I've not checked the output yet), but the audio runs into a `No such filter: ''` error 

`
ffmpeg     -vsync 0     -i "f1.mp4"     -i "f2.mp4"     -i "f3.mp4"     -filter_complex          [0]atrim=0:234.695[0:a];          [1]atrim=0:237.3946[1:a];          [2]atrim=0:394.413714[2:a];          [0:a][1:a]acrossfade=d=1:c1=tri:c2=tri[a1];          [a1][2:a]acrossfade=d=1:c1=tri:c2=tri[audio]"     -b:v 10M     -map "[audio]" "out.wav" 
`

```
[AVFilterGraph @ 0000019f4ac96ac0] No such filter: ''
Error initializing complex filters.
Invalid argument
 ```

This seems to be due to a missing between `-filter_complex` and `[0]atrim=..`


PS. Would be good if the UI included an option to include (or exclude) the \ characters at the end of each line.

**Comment by alanbqs** [comment]
Also - the final ffmpeg command in the trio is missing a space before the -c:v
And I get a problem with out.mp4 being both an input and an output - I had to change the command to `ffmpeg -i "out.mp4" -i "out.wav" -c:v copy -c:a aac output.mp4`

(it would have been better to call the temporary working files tmp.wav and tmp.mp4 in hidesight)

**Comment by Romander** [comment]
@alanbqs 
_And I get a problem with out.mp4 being both an input and an output - I had to change the command to ffmpeg -i "out.mp4" -i "out.wav" -c:v copy -c:a aac output.mp4_
fixed

_(it would have been better to call the temporary working files tmp.wav and tmp.mp4 in hidesight)_
changed

_This seems to be due to a missing between -filter_complex and [0]atrim=.._
fixed

_PS. Would be good if the UI included an option to include (or exclude) the \ characters at the end of each line._
added

**Comment by alanbqs** [comment]
Thanks Romander - great work! :-)
