### ISSUE TITLE
Video offset gets rounded up

### ISSUE THREAD

**Issue by EnderRL** [Romander/ffmpeg-script-generator#2]
Recently I discovered your website which help auto generating command for video fade and audio crossfade, it was a lifesaver for me.
But, theres one critical problem, the video offset. I was joining multiple videos like 4 videos at once and I used your script to fade and acrossfade the videos. Yes it is indeed taking a lot of time to join for almost a week long video, only to find out the audio is not syncing with the video.

I used 1 duration fade for the setting, and found out it can delay for like 3 seconds for 4 video.
Then i spent a lot of time figuring out why does this happen. I tried spliting the video and the audio to find out the output duration, did a lot of discoveries on the internet and lots of math, only to find out that the offset had to be -1 second.

Example, I had this script generated from your website:
name:
2024-04-09_11-08-02.mp4
duration:
10.273177
(seconds, float)
-
name:
2024-04-09_11-08-14.mp4
duration:
35.673177
(seconds, float)
-
name:
2024-04-09_11-08-51.mp4
duration:
37.639844
(seconds, float)
-
name:
2024-04-09_11-09-29.mp4
duration:
26.10651
(seconds, float)
-
name:
2024-04-09_11-09-57.mp4
duration:
30.373177
(seconds, float)
-
name:
2024-04-09_11-10-29.mp4
duration:
21.839844
(seconds, float)
-
Total video duration will be `161.905729` with no fade transition.
Since it has 6 videos, it will be -6s, means it supposed to be `155.905729` long.

`ffmpeg -vsync 0 -c:v hevc_cuvid -i 2024-04-09_11-08-02.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-14.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-51.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-29.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-57.mp4 -c:v hevc_cuvid -i 2024-04-09_11-10-29.mp4 -filter_complex "[0]settb=AVTB[0:v];[1]settb=AVTB[1:v];[2]settb=AVTB[2:v];[3]settb=AVTB[3:v];[4]settb=AVTB[4:v];[5]settb=AVTB[5:v];[0]atrim=0:10.273177[0:a];[1]atrim=0:35.673177[1:a];[2]atrim=0:37.639844[2:a];[3]atrim=0:26.10651[3:a];[4]atrim=0:30.373177[4:a];[5]atrim=0:21.839844[5:a];[0:v][1:v]xfade=transition=fade:duration=0.5:offset=9.773[v1];[v1][2:v]xfade=transition=fade:duration=0.5:offset=44.946[v2];[v2][3:v]xfade=transition=fade:duration=0.5:offset=82.086[v3];[v3][4:v]xfade=transition=fade:duration=0.5:offset=107.693[v4];[v4][5:v]xfade=transition=fade:duration=0.5:offset=137.566,format=yuv420p[video];[0:a][1:a]acrossfade=d=0.5:c1=tri:c2=tri[a1];[a1][2:a]acrossfade=d=0.5:c1=tri:c2=tri[a2];[a2][3:a]acrossfade=d=0.5:c1=tri:c2=tri[a3];[a3][4:a]acrossfade=d=0.5:c1=tri:c2=tri[a4];[a4][5:a]acrossfade=d=0.5:c1=tri:c2=tri[audio]" -c:v hevc_nvenc -rc vbr -cq 30 -qmin 30 -qmax 30 -profile:v main -pix_fmt yuv420p -b:v 0K -b_ref_mode 0 -movflags faststart -c:a libopus -ar 48000 -b:a 96k -map "[audio]" -map "[video]" a.mp4`

the video and audio were out of sync,
then i split the video and audio command, found out that:

1. The video was `00:02:39.43` long
2. The audio was `00:02:31.34` long

then I messed with the offset on the xfade filter based on how many videos to join and then offset -1.1s on the first transition, -2.2s on the second transition and so on:
`ffmpeg -vsync 0 -c:v hevc_cuvid -i 2024-04-09_11-08-02.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-14.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-51.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-29.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-57.mp4 -c:v hevc_cuvid -i 2024-04-09_11-10-29.mp4 -filter_complex "[0]settb=AVTB[0:v];[1]settb=AVTB[1:v];[2]settb=AVTB[2:v];[3]settb=AVTB[3:v];[4]settb=AVTB[4:v];[5]settb=AVTB[5:v];[0]atrim=0:10.273177[0:a];[1]atrim=0:35.673177[1:a];[2]atrim=0:37.639844[2:a];[3]atrim=0:26.10651[3:a];[4]atrim=0:30.373177[4:a];[5]atrim=0:21.839844[5:a];[0:v][1:v]xfade=transition=fade:duration=1:offset=9.273[v1];[v1][2:v]xfade=transition=fade:duration=1:offset=43.946[v2];[v2][3:v]xfade=transition=fade:duration=1:offset=80.586[v3];[v3][4:v]xfade=transition=fade:duration=1:offset=105.693[v4];[v4][5:v]xfade=transition=fade:duration=1:offset=135.066,format=yuv420p[video];[0:a][1:a]acrossfade=d=1:c1=tri:c2=tri[a1];[a1][2:a]acrossfade=d=1:c1=tri:c2=tri[a2];[a2][3:a]acrossfade=d=1:c1=tri:c2=tri[a3];[a3][4:a]acrossfade=d=1:c1=tri:c2=tri[a4];[a4][5:a]acrossfade=d=1:c1=tri:c2=tri[audio]" -c:v h264_nvenc -rc vbr -cq 30 -qmin 30 -qmax 30 -profile:v main -pix_fmt yuv420p -b:v 0K -b_ref_mode 0 -movflags faststart -c:a libopus -ar 48000 -b:a 96k -map "[audio]" -map "[video]" a.mp4`,
i got nearly the duration with the audio, `00:02:31.33`
same with the audio:
`ffmpeg -vsync 0 -c:v hevc_cuvid -i 2024-04-09_11-08-02.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-14.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-51.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-29.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-57.mp4 -c:v hevc_cuvid -i 2024-04-09_11-10-29.mp4 -filter_complex "[0]atrim=0:10.273177[0:a];[1]atrim=0:35.673177[1:a];[2]atrim=0:37.639844[2:a];[3]atrim=0:26.10651[3:a];[4]atrim=0:30.373177[4:a];[5]atrim=0:21.839844[5:a];[0:a][1:a]acrossfade=d=1:c1=tri:c2=tri[a1];[a1][2:a]acrossfade=d=1:c1=tri:c2=tri[a2];[a2][3:a]acrossfade=d=1:c1=tri:c2=tri[a3];[a3][4:a]acrossfade=d=1:c1=tri:c2=tri[a4];[a4][5:a]acrossfade=d=1:c1=tri:c2=tri[audio]" -c:v h264_nvenc -b:v 10M -map "[audio]" temp.wav`
ofc I got `00:02:31.34`

BUT, the audio still end up not syncing with the video

then i try the -1s offset on the video again:
`ffmpeg -vsync 0 -c:v hevc_cuvid -i 2024-04-09_11-08-02.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-14.mp4 -c:v hevc_cuvid -i 2024-04-09_11-08-51.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-29.mp4 -c:v hevc_cuvid -i 2024-04-09_11-09-57.mp4 -c:v hevc_cuvid -i 2024-04-09_11-10-29.mp4 -filter_complex "[0]settb=AVTB[0:v];[1]settb=AVTB[1:v];[2]settb=AVTB[2:v];[3]settb=AVTB[3:v];[4]settb=AVTB[4:v];[5]settb=AVTB[5:v];[0:v][1:v]xfade=transition=fade:duration=1:offset=8.273[v1];[v1][2:v]xfade=transition=fade:duration=1:offset=41.946[v2];[v2][3:v]xfade=transition=fade:duration=1:offset=77.586[v3];[v3][4:v]xfade=transition=fade:duration=1:offset=101.693[v4];[v4][5:v]xfade=transition=fade:duration=1:offset=130.066,format=yuv420p[video]" -c:v h264_nvenc -rc vbr -cq 30 -qmin 30 -qmax 30 -profile:v main -pix_fmt yuv420p -b:v 0K -b_ref_mode 0 -movflags faststart -c:a libopus -ar 48000 -b:a 96k -map "[video]" temp.mp4`
and i got `00:02:31.83`

AND this is how it managed to sync with the audio somehow.
Update on this part:
After removing the atrim, I realised the duration of the video and the audio is not the same, that's why atrim is still needed.

Conclusion:
WHAT THE HECK is even going on lol. Been driving my mind crazy for the whole day.
I still can't confirm whether is my video's duration problem or the generative script -1s offset bug. I remember I did managed to work on first try but maybe I didn't even notice about the audio whether is sync or not, that was just 2 videos together so is not obvious, only when there's more videos to join. But in the end, I still managed to have a work around on this issue. 
Please confirm this issue, Thanks!

Update 1: I did a lot of edits on this post since I keep experimenting with the values I go right now. I originally had this issue using 0.5 for the duration settings, but I think 1s duration could explain the issue better, does that mean 0.5s duration transition = -0.5s offset? i don't even know anymore lol.

**Comment by Romander** [comment]
Hi Ryan, 

Thanks for your message. It is great digging work you did. I will try to look into it at the weekend when I have free time. 

Thanks again. 

P.S. I remember that I had the same problem with the sync. Maybe I need to refresh the algorithm with the knowledge I got in my other project.

**Comment by EnderRL** [comment]
Another update:
Recently I just found that I had to check for the audio length first, then recalculate the offset.
But, different kind of videos had different duration.
I had my one week long video being processed with the edited -1s offset, but it was still 2s early than the audio.
The audio was `179:58:48.38` long, then
The video I offset -1s was `179:58:46.53`.

Since it became 2s earlier, I had to fallback to -0.5s offset, and the result:
The video was `179:58:48.07` long,
and I nearly got the audio to sync, just 0.3s early too.

New conclusion:
I think the first step of xfade transition multiple videos is:
1) Export the audio first, then get the total duration length
2) Calculate the total time the video will be output.
- If for 5 videos and it has 2 seconds delay (early), all offset with your current generative algorithm will be offset -0.5s (Total will be +2s the duration).
- If it late for 2 seconds, then it will be the opposite, +0.5s (Total will be -2s the duration)
3) Then combine audio and video together.

Hope this additional details could help you check the issue more easily!

**Comment by EnderRL** [comment]
Another update:
Forget about the offset thing on the main post.
After researching even more from the command to the internet, I know that:
1) atrim is so important that it match the duration of the video since the duration of the video and the audio doesn't even match
(ffprobe -i example.mp4 -show_entries stream=codec_type,duration -of compact=p=0:nk=1)
2) for my current project, there's one file that i used has the trim option [-ss] (because the end of the video got corrupted), so i am afraid that when i used the end of trim duration, the offset will not match.
3) I had followed this [forum](https://stackoverflow.com/questions/63553906/merging-multiple-video-files-with-ffmpeg-and-xfade-filter) and tried doing the offset again, then compare with the generated command. 
My biggest concern is that the generated command of the value had rounded up, example:
I have a value of `174092.806511`, but then it seems to round it up to `174092.807` 3 decimals.
It's better to have full value instead of the round up, especially for someone who used 0.5 offset, that will be the problem. So that's what I concern about it.

The video is really big that I had to wait for 20 hours to check if it's successful or not. This problem took me more than 1 week which I didn't expect it will turned out this way.

That's all about my update.
(Until now I am still waiting for my hypostasis to be confirmed)

### Last update:
My hypostasis is indeed correct, is just the round up issue. Now I had finally managed to get the exact same total duration of the video and the audio joined.

This is what i used for the command:
Video:
ffmpeg -c:v hevc_cuvid -i "2024-03-29_03-40-57.remuxed.mp4" -c:v hevc_cuvid -i "2024-03-31_04-08-13.remuxed.mp4" -c:v hevc_cuvid -ss 00:00:00 -to 32:10:15.506511 -i "2024-04-03_15-03-35.remuxed.mp4" -c:v hevc_cuvid -i "2024-04-04_23-20-10.remuxed.mp4" -filter_complex "[0]settb=AVTB,fps=15/1[0:v];[1]settb=AVTB,fps=15/1[1:v];[2]settb=AVTB,fps=15/1[2:v];[3]settb=AVTB,fps=15/1[3:v];[0:v][1:v]xfade=transition=fade:duration=1:offset=174091.80651[v1];[v1][2:v]xfade=transition=fade:duration=1:offset=472568.9265[v2];[v2][3:v]xfade=transition=fade:duration=1:offset=588383.4325,format=yuv420p[video]" -map [video] -s 1280x720 -c:v hevc_nvenc -rc vbr -cq 30 -qmin 30 -qmax 30 -profile:v main -pix_fmt yuv420p -b:v 0K -b_ref_mode 0 -movflags faststart "tmp_720p.mp4"

And I got the duration `179:58:49.52`

Audio:
ffmpeg -c:v hevc_cuvid -i "2024-03-29_03-40-57.remuxed.mp4" -c:v hevc_cuvid -i "2024-03-31_04-08-13.remuxed.mp4" -c:v hevc_cuvid -ss 00:00:00 -to 32:10:15.506511 -i "2024-04-03_15-03-35.remuxed.mp4" -c:v hevc_cuvid -i "2024-04-04_23-20-10.remuxed.mp4" -filter_complex "[0:a]aresample=async=1:first_pts=0,apad,atrim=0:174092.806511[a0];[1:a]aresample=async=1:first_pts=0,apad,atrim=0:298478.106511[a1];[2:a]aresample=async=1:first_pts=0,apad,atrim=0:115815.506000[a2];[3:a]aresample=async=1:first_pts=0,apad,atrim=0:59546.106511[a3];[a0][a1]acrossfade=d=1:c1=tri:c2=tri[1a];[1a][a2]acrossfade=d=1:c1=tri:c2=tri[2a];[2a][a3]acrossfade=d=1:c1=tri:c2=tri[audio]" -map [audio] -c:a libopus -ar 48000 -b:a 96k "96k.opus"

And the duration `179:58:49.52`

Joining together:
ffmpeg -i "tmp_720p.mp4" -i "96k.opus" -c:v copy -movflags faststart -c:a copy "720p.mp4" (Bad idea, but since the issue, I only used it to test the sync)

Result: Synced as expected

**Comment by Romander** [comment]
Hi Ryan,

You did great job. I removed rounding in the code. I checked if it would help but the syncing was not worked. But additionally I added to the script from your examples `aresample=async=1:first_pts=0,apad` to the single `atrim` filter in the audio sript. And syncing worked. I checked on hour long video. `aresample=async=1:first_pts=0:` Resamples audio to synchronize with the video and I think this is the main which helped together with removing rounding.

Thanks again.

P.S You can check on the site updated version https://romander.github.io/ffmpeg-script-generator/

**Comment by EnderRL** [comment]
Thanks for resolving the issue.
I had verified that the updated site version is working well and the result, the video finally synced perfectly with the audio.

I have another recommendation on getting video duration, is to use this command:
`ffprobe -i clip.mp4 -show_entries stream=codec_type,duration -of compact=p=0:nk=1`
This will output both video and audio duration since both doesn't always match.

By the original command that everyone used:
`ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 input.mp4`
I only get the longest duration:
174092.806511

but by my new command, I can get both video and audio duration:
video|174092.806511
audio|174091.840000

Sometimes the duration of the audio will be longer than the video
In the end, the atrm will do the job anyways, but for me, I will take the video as the duration of the video.

Thanks again for resolving the issue!
